theme: minima
title: STAA57 Introduction to Data Science 
github_username: damouras 

docs_list_title: Course Material
docs:

- title: Lectures
  url: lectures.html

- title: Assignments
  url: assignments.html

- title: Project
  url: project.html
