theme: minima

title: STAA57 Introduction to Data Science 
github_username: damouras 

header_pages:
  - project.md
  - lectures.md
  - syllabus.md

tabs: 
    tab1:
        name: lectures
        title: Page One
        source: source1
    tab2:
        name: assignments
        title: Page Two
        source: source2
        content: >
            ## Headline

            This is the content of the second tab, it is defined in the frontmatter as **markdown**.

            A Link: [link](https://foo.bar.org)
